version: '3.4'

services:
  dockerenvironment:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - RootProperty=minimalapi-root-value
      - RootSettings__SampleVariable=minimalapi-variable-value
      - ConnectionStrings__SqlConnection=Server=minimal.db;Database=minimal_db;User Id=TEST;Password=TEST!
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro